config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'static_pages#home'

	resources :companies, only: [:show, :edit, :update] do
	  member do
	    get :employees
	    get :summary_report
	  end
	end

	resources :employees, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :employees, -> { order 'employees.id' }, through: :departments
	has_many :summary_reports

	has_paper_trail :on => [:update], :skip => [:updated_at]
  strip_attributes :collapse_spaces => true

	validates :name, presence: true, uniqueness: true

end

app/models/department.rb
class Department < ApplicationRecord
	belongs_to :company
	has_many :employees, dependent: :destroy

	has_paper_trail :on => [:update], :skip => [:updated_at]
  strip_attributes :collapse_spaces => true

  validates :name, presence: true, uniqueness: {scope: :company}

	default_scope { includes(:company) }
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :user, dependent: :destroy
	belongs_to :department
	belongs_to :role

	delegate :company, :to => :department, :allow_nil => true

	has_paper_trail :on => [:update], :skip => [:updated_at]
  strip_attributes :collapse_spaces => true

  validates_presence_of :name, :address_street, :phone_home, :title, :salary, :bonus
 	validates_format_of :phone_home, :with => /\A\d{3}\.\d{3}\.\d{4}\Z/i
	validates_numericality_of :salary, :bonus, only_integer: true, greater_than_or_equal_to: 0, allow_blank: true


	default_scope { includes([:role, :department]) }

end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord

	validates :name, presence: true, uniqueness: true

	def administrator?
		name == "Administrator"
	end
	
	def to_s
		name
	end
end

app/models/summary_report.rb
class SummaryReport < ActiveRecord::Base
  self.table_name = 'v_summary_report'

  belongs_to :company

  protected

  def readonly?
    true
  end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :timeoutable, :trackable

  has_one :employee, dependent: :destroy
	delegate :company, :to => :employee, :allow_nil => true
	delegate :role, :to => :employee, :allow_nil => true
  
  default_scope { includes(:employee) }

  validates :email, uniqueness: true, presence: true, format: Devise::email_regexp
  validates :password, presence: true

  def to_login
  	"#{employee&.name} - #{company&.name}, #{employee&.role}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  # after_action :verify_authorized, unless: :devise_controller?

  before_action :set_paper_trail_whodunnit

  def user_for_paper_trail
    # logged_in? ? current_member.id : 'Public user'  # or whatever
  	current_user.id if current_user

  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  before_action :set_company

  def update
    if @company.update(company_params)
      redirect_to @company, flash: {success: "Company successfully updated"}
    else
      render :edit 
    end
    rescue StandardError => e 
      flash.now[:error] = "Error saving Company. #{e}"
      render :edit     
  end

  def employees
    @employees = @company.employees
  end

  def summary_report
    @records = @company.summary_reports.where("salary_rank <= ?", 3)
  end

  private

  def set_company
     @company = Company.find(params[:id])
     authorize @company
  end

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  before_action :set_employee, 
                :set_departments,
                :set_roles

  def update
    
    authorize @employee

    if @employee.update(employee_params)
      redirect_to @employee, flash: {success: "Employee successfully updated"}
    else
      render :edit 
    end
    rescue StandardError => e 
      flash.now[:error] = "Error saving Employee. #{e}"
      render :edit     
  end

  private

  def set_employee
     @employee = Employee.find(params[:id])
     authorize @employee
  end

  def set_departments
     @departments = Department.where(company_id: @employee.company)
  end

  def set_roles
    @roles = Role.all
  end

  def employee_params
    params.require(:employee).permit(policy(@employee).permitted_attributes)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  layout "signin"

  before_action :set_users, only: [:new, :create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
  def set_users
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }

  def bootstrap_alert_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def link_to_if(*args,&block)
      args.insert 1, capture(&block) if block_given?

      super *args
  end  

end

app/views/companies/_fields.html.erb
<%= render "shared/error_messages", object: f.object %>
<div class="row">
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :name, "name:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>    
  </div>
</div>
     

app/views/companies/_header.html.erb
<h1 style="display:inline-block;">Company: <%= @company.name %></h1>	

app/views/companies/edit.html.erb
<div>
	<%= render "header" %>		
	<h4 class="pull-right"><%= fa_icon("cancel") %> <%= link_to 'cancel', company_path(@company) %></h4>
</div>

<%= form_for(@company, url: company_path(@company), html: {class: "form-horizontal", role: "form"}) do |f| %>
	<%= render "fields", f: f %>
 	  <div class="form-group">
	    <div class="col-xs-offset-2 col-xs-5">
	      <%= f.submit "Update Company", class: "btn btn-primary btn-large btn-block", data: { disable_with: "Please wait..." } %>
	    </div>
	  </div>	  

<% end %>

app/views/companies/employees.html.erb
<%= render "header" %>	
<h4 class="page-header"> Employees </h4>	
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>address</th>
      <th>phone</th>
      <th>department</th>
      <th>role</th>
      <th>title</th>
      <th>salary</th>
      <th>bonus</th>      
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |emp| %>
	    <tr>
	    	<td><%= link_to emp.id, employee_path(emp), class: 'btn btn-default' %></td>
	    	<td><%= emp.name %></td>
	    	<td><%= emp.address_street %></td>
	    	<td><%= emp.phone_home %></td>
	    	<td><%= emp.department.name %></td>
	    	<td><%= emp.role.name %></td>
	    	<td><%= emp.title %></td>
	    	<td><%= emp.salary %></td>
	    	<td><%= emp.bonus %></td>
	    </tr>    	
    <% end %>
  </tbody>
</table>

app/views/companies/show.html.erb
<div>
	<%= render "header" %>		
	<h4 class="pull-right"><%= fa_icon("edit") %> <%= link_to 'edit', edit_company_path(@company) %></h4>
</div>

<div class="row">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">company</a></li>
    <li role="presentation"><a href="#versions" aria-controls="versions" role="tab" data-toggle="tab">Data changes <span class='badge'><%= @company.versions.count %></span></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
    	<br>
			<div class="row">
				<form class="form-horizontal" role="form">
					<div class="col-xs-12">
						<div class="col-xs-5">
						  <div class="form-group">
								<%= label_tag :name, "name:", options={class:"col-xs-4 control-label"} %>
								<div class="col-xs-8">
									<p class="form-control-static"><%= @company.name %></p>
								</div>
						  </div>
						</div>
						<div class="col-xs-1"></div>
						<div class="col-xs-5">
						</div>	
					</div>


				</form>
			</div>

    </div>
    <div role="tabpanel" class="tab-pane" id="versions"><br>
			<div class="col-xs-12">
				<%= render "shared/paper_trail", versions: @company.versions %>
			</div>
    </div>
  </div>

</div>

app/views/companies/summary_report.html.erb
<%= render "header" %>	
<h4 class="page-header"> Summary Report </h4>	
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>department</th>
      <th>employee</th>
      <th>salary</th>     
    </tr>
  </thead>

  <tbody>
    <% @records.each do |r| %>
	    <tr>
	    	<td><%= link_to r.employee_id, employee_path(r.employee_id), class: 'btn btn-default' %></td>
	    	<td><%= r.department_name %></td>
	    	<td><%= r.employee_name %></td>
	    	<td><%= r.salary %></td>
	    </tr>    	
    <% end %>
  </tbody>
</table>

app/views/employees/_comp_fields.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :company, "company:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.object.company&.name %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :department, "department:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.select(:department_id, @departments.collect{ |d| [d.name, d.id] }, {:include_blank => 'Select department' }, { class: "form-control" } ) %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :role, "role:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.select(:role_id, @roles.collect{ |r| [r.name, r.id] }, {:include_blank => 'Select status' }, { class: "form-control" } ) %>
      </div>
    </div>    
  </div>  
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :title, "title:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :salary, "salary:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :salary, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :bonus, "bonus:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :bonus, class: "form-control" %>
      </div>
    </div>    
  </div>
</div>

app/views/employees/_comp_fields_readonly.html.erb
<div class="row">
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :company, "company:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.company&.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :department, "department:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.department&.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :role, "role:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.role&.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :title, "title:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.title %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :salary, "salary:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.salary %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="col-xs-5">
        <div class="form-group">
          <%= label_tag :bonus, "bonus:", options={class:"col-xs-4 control-label"} %>
          <div class="col-xs-8">
            <p class="form-control-static"><%= @employee.bonus %></p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/employees/_fields.html.erb
<%= render "shared/error_messages", object: f.object %>

<div class="row">
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :name, "name:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :address_street, "street address:", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :address_street, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="col-xs-12">
    <div class="form-group">
      <%= f.label :phone_home, "phone(home):", class: "col-xs-2 control-label" %>
      <div class="col-xs-3">
        <%= f.text_field :phone_home, class: "form-control" %>
      </div>
    </div>    
  </div>
</div>

<div class="row">
	<div class="col-xs-12">
			<h4 class="page-header"> Position information </h4>			
	</div>
</div>     

<%= render policy(f.object).edit_compensation? ? "comp_fields" : "comp_fields_readonly", f: f %>

app/views/employees/edit.html.erb
<div>
	<h1 style="display:inline-block;">Employee id: <%= @employee.id %></h1>			
	<h4 class="pull-right"><%= fa_icon("cancel") %> <%= link_to 'cancel', employee_path(@employee) %></h4>
</div>

<%= form_for(@employee, url: employee_path(@employee), html: {class: "form-horizontal", role: "form"}) do |f| %>
	<%= render "fields", f: f %>
 	  <div class="form-group">
	    <div class="col-xs-offset-2 col-xs-5">
	      <%= f.submit "Update Employee", class: "btn btn-primary btn-large btn-block", data: { disable_with: "Please wait..." } %>
	    </div>
	  </div>	  
<% end %>

app/views/employees/show.html.erb
<div>
	<h1 style="display:inline-block;">Employee id: <%= @employee.id %></h1>			
	<h4 class="pull-right"><%= fa_icon("edit") %> <%= link_to 'edit', edit_employee_path(@employee) %></h4>
</div>

<div class="row">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">employee</a></li>
    <li role="presentation"><a href="#versions" aria-controls="versions" role="tab" data-toggle="tab">Data changes <span class='badge'><%= @employee.versions.count %></span></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
    	<br>
			<div class="row">
				<form class="form-horizontal" role="form">
					<div class="col-xs-12">
						<div class="col-xs-5">
						  <div class="form-group">
								<%= label_tag :name, "name:", options={class:"col-xs-4 control-label"} %>
								<div class="col-xs-8">
									<p class="form-control-static"><%= @employee.name %></p>
								</div>
						  </div>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="col-xs-5">
						  <div class="form-group">
								<%= label_tag :address_street, "street address:", options={class:"col-xs-4 control-label"} %>
								<div class="col-xs-8">
									<p class="form-control-static"><%= @employee.address_street %></p>
								</div>
						  </div>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="col-xs-5">
						  <div class="form-group">
								<%= label_tag :phone_home, "phone(home):", options={class:"col-xs-4 control-label"} %>
								<div class="col-xs-8">
									<p class="form-control-static"><%= @employee.phone_home %></p>
								</div>
						  </div>
						</div>
					</div>
				</form>
			</div>
			<div class="row">
				<div class="col-xs-12">
						<h4 class="page-header"> Position information </h4>			
				</div>
			</div>

			<%= render "comp_fields_readonly", f: @employee %>

    </div>
    <div role="tabpanel" class="tab-pane" id="versions"><br>
			<div class="col-xs-12">
				<%= render "shared/paper_trail", versions: @employee.versions %>
			</div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to(root_path, class: 'navbar-brand')  do %>
        <%= image_tag "logo-signin.png", height: 30 %>
      <% end %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav ">
        <% if policy(current_user.company).show? %>
          <li><%= link_to 'Company Information', company_path(current_user.company) %></li>
        <% end %>             
        <li><%= link_to 'Employee Profile', employee_path(current_user.employee) %></li>  
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="accountMenu" >  
          <%= current_user.employee&.name %>     
          <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="accountMenu">
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../favicon.ico"> -->


    <title><%# = yield(:page_title) %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

  	<%= render 'layouts/header' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-2 sidebar">
          <%= yield(:sidebar) %>    							
        </div>
        <div class="col-xs-10 col-xs-offset-2 main">

          <% flash.delete(:timedout).each do |message_type, message| %>
              <%= render :layout => '/shared/alert_messages', :locals => { :type => message_type, :dismiss => true } do %>
              <%= message %>
            <% end %> 
          <% end %>  

        	<%= yield(:page_header) %>
          <%= yield %>
          
        </div>
      </div>
    </div>
  </body>

    <script>
      $( document ).ready(function() {
        $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
            $(".alert-success").alert('close');
        });
        $(".alert-info").fadeTo(2000, 500).slideUp(500, function(){
            $(".alert-info").alert('close');
        });
        $('input:enabled:visible:first').focus();
        $('[data-toggle="popover"]').popover();
      });
    </script>

</html>

app/views/layouts/companies.html.erb
<% content_for :sidebar do %>
<%
  render_navigation do |primary|

	  primary.dom_class = 'nav nav-sidebar'

	  primary.item :employees,
	  							"Employees", 
	  							employees_company_path(@company)

  	primary.item :summary_report, 
  							'Summary Report', 
  							summary_report_company_path(@company)
  end
%> 
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/employees.html.erb
<% content_for :sidebar do %>
<%
  render_navigation do |primary|

	  primary.dom_class = 'nav nav-sidebar'

  end
%> 
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--     <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Demo</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>

    <style>
       body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
      }

      .form-signin {
        max-width: 430px;
        padding: 15px;
        margin: 0 auto;
      }
      .form-signin .form-signin-heading,
      .form-signin .form-signin-logo,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      
      .form-signin-heading {
        text-align: center;
      }

      .form-signin-logo {
        display: block;
        margin-left: auto;
        margin-right: auto 
      }        


      .form-signin .checkbox {
        font-weight: normal;
      }
      .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
           -moz-box-sizing: border-box;
                box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }   
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <div class="container-fluid">

      <% flash.delete(:timedout).each do |message_type, message| %>
          <%= render :layout => '/shared/alert_messages', :locals => { :type => message_type, :dismiss => true } do %>
          <%= message %>
        <% end %> 
      <% end %> 

      <%= yield %>

    </div>
  </body>
</html>

app/views/shared/_alert_messages.html.erb
	<div class="alert <%= bootstrap_alert_class_for(type) %>" role="alert">
		<% if dismiss %>
	    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	      <span aria-hidden="true">
	        <i class="icon fa fa-times-circle fa-md"></i><!-- &times; -->
	      </span>
	    </button>
	  <% end %>              
	  <%= yield %>
	</div>



           

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		
		<%= render :layout => '/shared/alert_messages', :locals => {:type => :error, :dismiss => false} do %>
		  <strong><%=  "Error".pluralize(object.errors.count) %> with this form.</strong>
		<% end %> 

		<ul>
			<% object.errors.full_messages.each do |err| %>
				<li><%= err %></li>				
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_paper_trail.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>event</th>
      <th>field</th>
      <th>old value</th>
      <th>new value</th>
      <th>user</th>
      <th>date/time</th>
    </tr>
  </thead>

  <tbody>
    <% versions.each do |v| %>
    	<% if (v.event == "update") %>
        <% v.changeset.keys.each do |k| %>
	        <tr>
	        	<td><%= v.id %></td>
	        	<td><%= v.event %></td>
	        	<td><%= k %></td>
	        	<td><%= v.changeset[k][0] %></td>
	        	<td><%= v.changeset[k][1] %></td>
	        	<td><%= v.whodunnit %></td>
	        	<td><%= v.created_at.strftime("%m/%d/%Y %I:%M%p") %></td>
	        </tr>
        <% end %>			      	
    	<% else %>
	        <tr>
	        	<td><%= v.id %></td>
	        	<td><%= v.event %></td>
	        	<td></td>
	        	<td></td>
	        	<td></td>
	        	<td><%= v.whodunnit %></td>
	        	<td><%= v.created_at.strftime("%m/%d/%Y %I:%M%p") %></td>
	        </tr>
    	<% end %>			      
    <% end %>
  </tbody>
</table>

app/views/static_pages/home.html.erb
<div class="row">
	<div class="col-xs-12">
	 	<h2 class="page-header">Home</h2>
	</div>
</div>